### ISSUE TITLE
Newbie Guide 

### ISSUE THREAD

**Issue by stevef1uk** [flynn-archive/flynn-website#1]
Hi,

I have been monitoring this project for a while and would like to try out the new version, but I can't see how to start. Perhaps others are in the same position and could do with a bootstrap guide for newbies.

Regards

Steve

**Comment by danielsiders** [comment]
@stevef1uk Thanks for reaching out. We're in the final phase (hours) from launching all the getting started stuff along with the preview release. Check back tomorrow (or you get the email if you're on the mailing list).

**Comment by stevef1uk** [comment]
Thanks. Great news. I could see from the repos that you must be close :-)
